add encoding of string literals to sum types of unary constructors
purescript-contrib/purescript-argonaut-generic pull request #3
Opened 2017-07-15 09:41 UTC by justinwoo

Adds encoding of enum-style sum types and provides a function argument for how tag names are to be transformed.

2017-07-15 11:24 UTC, garyb requested changes

2017-07-15 11:24 UTC, garyb commented on src/Data/Argonaut/Decode/Generic/Rep.purs
> +  `decodeLiteralSum` can't be used without sum types, where all of the constructors aren't unary. This is because a string literal cannot be encoded into a product type.
Hello multi-negative! 😜 

How about something like:

```
type FailMessage = """`decodeLiteralSum` can only be used with sum types where all of the constructors are unary. A string literal cannot sensibly encode a product type."""
```

for these messages?

2017-07-15 11:24 UTC, garyb commented on src/Data/Argonaut/Decode/Generic/Rep.purs
> +decodeLiteralSum tagNameTransform = map Rep.to <<< decodeLiteral tagNameTransform
Do you think it makes sense to provide a transform? I'd keep it simple and drop that. If you're using generics you already can't really control the format, so providing something to customise it for this particular case seems a little odd.

2017-07-15 11:27 UTC, justinwoo commented on src/Data/Argonaut/Decode/Generic/Rep.purs
> +decodeLiteralSum tagNameTransform = map Rep.to <<< decodeLiteral tagNameTransform
It gets really sad if you can't convert things like `CONST_STRING` to `ConstString` and `MYSTRING` to `MyString` though, ending up with either the ugliest constructors (if not illegal) or having to provide extra things just to work with some serialized data

2017-07-15 11:28 UTC, justinwoo commented on src/Data/Argonaut/Decode/Generic/Rep.purs
> +  `decodeLiteralSum` can't be used without sum types, where all of the constructors aren't unary. This is because a string literal cannot be encoded into a product type.
Ah, sure. Probably best to get rid of the white space too since the compiler doesn't strip them

2017-07-15 11:37 UTC, garyb commented on src/Data/Argonaut/Decode/Generic/Rep.purs
> +decodeLiteralSum tagNameTransform = map Rep.to <<< decodeLiteral tagNameTransform
I guess that's what I'm not understanding perhaps... why would you need to do that? If you're using generics it seems like it's something you would have serialized in the first place, so the specific encoding should be the same anyway?

It just seems a bit odd to me, as if you're using this argument you'd probably need an iso anyway, so you could just combine the encode/decode with a `map` as appropriate.

2017-07-19 10:35 UTC, garyb commented on src/Data/Argonaut/Decode/Generic/Rep.purs
> +decodeLiteralSum tagNameTransform = map Rep.to <<< decodeLiteral tagNameTransform
How about we provide the current functions as `decodeLiteralSum'` or `decodeLiteralSumWithTransform` or something, and then a version with `id` applied as the normally named version?

2017-07-19 17:20 UTC, justinwoo commented on src/Data/Argonaut/Decode/Generic/Rep.purs
> +decodeLiteralSum tagNameTransform = map Rep.to <<< decodeLiteral tagNameTransform
That sounds fine to me, I'll try to get it pushed up

2017-07-19 17:51 UTC, justinwoo commented
Pushed up the changes. Also realized this should say "nullary constructor", oops.

2017-07-19 19:04 UTC, garyb requested changes
Almost there!

2017-07-19 19:04 UTC, garyb commented on src/Data/Argonaut/Decode/Generic/Rep.purs
> +type FailMessage = """`decodeLiteralSum` can only be used with sum types, where all of the constructors aren't nullary. This is because a string literal cannot be encoded into a product type."""
> where all of the constructors aren't nullary

Should be

> where all of the constructors **are** nullary

:smile:

2017-07-19 19:17 UTC, justinwoo commented
noooo

On Wed, Jul 19, 2017 at 10:04 PM, Gary Burgess <notifications@github.com>
wrote:

> *@garyb* requested changes on this pull request.
>
> Almost there!
> ------------------------------
>
> In src/Data/Argonaut/Decode/Generic/Rep.purs
> <https://github.com/purescript-contrib/purescript-argonaut-generic/pull/3#discussion_r128338354>
> :
>
> > +class DecodeLiteral r where
> +  decodeLiteral :: (String -> String) -> Json -> Either String r
> +
> +instance decodeLiteralSumInst :: (DecodeLiteral a, DecodeLiteral b) => DecodeLiteral (Rep.Sum a b) where
> +  decodeLiteral tagNameTransform j = Rep.Inl <$> decodeLiteral tagNameTransform j <|> Rep.Inr <$> decodeLiteral tagNameTransform j
> +
> +instance decodeLiteralConstructor :: (IsSymbol name) => DecodeLiteral (Rep.Constructor name (Rep.NoArguments)) where
> +  decodeLiteral tagNameTransform j = do
> +    let name = reflectSymbol (SProxy :: SProxy name)
> +    let decodingErr msg = "When decoding a " <> name <> ": " <> msg
> +    tag <- mFail (decodingErr "could not read string for constructor") (toString j)
> +    when (tag /= tagNameTransform name) $
> +      Left $ decodingErr "string literal " <> tag <> " had an incorrect value."
> +    pure $ Rep.Constructor (Rep.NoArguments)
> +
> +type FailMessage = """`decodeLiteralSum` can only be used with sum types, where all of the constructors aren't nullary. This is because a string literal cannot be encoded into a product type."""
>
> where all of the constructors aren't nullary
>
> Should be
>
> where all of the constructors *are* nullary
>
> 😄
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/purescript-contrib/purescript-argonaut-generic/pull/3#pullrequestreview-51009114>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACSS_jNOXgiUQO4PutB9fgcXx7F6WH3Rks5sPlNUgaJpZM4OY-GO>
> .
>

2017-07-19 19:19 UTC, justinwoo commented
Okay, fixed that nonsense. I'll just leave the single thing for now, and then maybe in the future we'll be able to have a catch-all instance for all the unsupported ones and make a more generic error.

2017-07-19 19:22 UTC, garyb approved these changes
Thanks!

2017-07-19 19:22 UTC, merged